from resources.controle_da_maquina.aba_controle_da_maquina import AbaControleDaMaquina
from resources.processamento_de_imagem.aba_processamento_de_imagem import AbaProcessamentoDeImagem
from resources.conversao_de_svg.aba_conversao_de_svg import AbaConversaoDeSvg
from resources.conversao_de_gcode.aba_conversao_de_gcode import AbaConversaoDeGcode
